### ISSUE TITLE
I have a trouble running your example

### ISSUE THREAD

**Issue by yajieC** [MPolaris/onnx2tflite#1]
I couldn't run it successfully, even running the example you provided got errors. Maybe something is wrong with my environment? Can you provide your specific environment？
The environment I use is:
torch=1.7.1
torchvision=0.8.2
tensorflow=1.15.2
onnx=1.8.0
onnx-simplifier=0.3.7
onnxrumtime=1.8.1
numpy=1.17.4
opencv-python=3.14.1.5

I have a problem with reproducing the example you provided. And the error is as follows:
![选区_825](https://user-images.githubusercontent.com/29948957/165478503-222faf16-9890-4156-bbfa-84d7c707786f.png)
![选区_826](https://user-images.githubusercontent.com/29948957/165478585-d29db493-551c-40f9-818a-9961411fb7ba.png)
![选区_827](https://user-images.githubusercontent.com/29948957/165480300-d7ac3c0f-400f-4d0c-9cdc-4257e626199b.png)

**Comment by MPolaris** [comment]
This trouble maybe cause by tensorflow 1.15, you can try tensorflow>=2.0, tensorflow 2.6 and tensorflow2.7 are ok.
