### ISSUE TITLE
clip_by_value=>relu6

### ISSUE THREAD

**Issue by duanshengliu** [MPolaris/onnx2tflite#14]
Hi，考虑一下把clip_by_value如果最大值是6则改成激活函数relu6感觉会更好些

**Comment by MPolaris** [comment]
好主意，是一个不错的优化trick，如果你有时间的话可以提交一个PR。

**Comment by PINTO0309** [comment]
The following five patterns can be optimized. If this is meddling, please ignore it.
- ReLU6
- ReLU
- Minimum
- Maximum
- Minimum + Maximum

https://github.com/PINTO0309/onnx2tf/blob/98620e50d3d2366b1b544cb1f9987b9cf4d3527b/onnx2tf/ops/Clip.py#L89-L122

**Comment by MPolaris** [comment]
> The following five patterns can be optimized. If this is meddling, please ignore it.
> 
> * ReLU6
> * ReLU
> * Minimum
> * Maximum
> * Minimum + Maximum
> 
> https://github.com/PINTO0309/onnx2tf/blob/98620e50d3d2366b1b544cb1f9987b9cf4d3527b/onnx2tf/ops/Clip.py#L89-L122

Thanks for your tricks, I will seriously consider your proposal.
