### ISSUE TITLE
关于保存的h5相比原始onnx较大的问题

### ISSUE THREAD

**Issue by duanshengliu** [MPolaris/onnx2tflite#16]
HI，MPolaris，我观察到保存的keras模型所占空间相比原始onnx大了不少，例如mobilenet_v2的h5模型接近88多M，原始模型大约13.9M，原因定位到是 Conv、Dense、Conv2DTranspose等 在导入权重时使用的是
`kernel_initializer=keras.initializers.Constant(weights),`
`bias_initializer='zeros' if bias is None else keras.initializers.Constant(bias),`
这种方式，这样使用会造成大量字符保存在h5模型中，占用空间大，netron打开也较慢
![image](https://user-images.githubusercontent.com/44742794/196180641-2a8419c1-8371-420c-be0a-0e0956cc8ef1.png)

建议都采用https://github.com/MPolaris/onnx2tflite/blob/main/layers/conv_layers.py#L166 深度可分离卷积实现方式：
 weights=[weights] 有bias则 weights=[weights, bias]
进行权重导入，感觉这样会更好些，实测修改后确实h5可以和原始onnx基本一样大，以上只是一定小小的建议

**Comment by MPolaris** [comment]
如果测试之后两个模型的输出是一致的，也就是不会导致精度问题，可以提交一个PR。
