### ISSUE TITLE
Transposed convolution output shape

### ISSUE THREAD

**Issue by AlexSS1001** [MPolaris/onnx2tflite#20]
Hi,

In the transposed convolution source code, the output shape is not the same as Pytorch, for same parameters. In order to solve this, I have moved the padding after self.conv call. This is for a tranposed convolution with kernel size [4, 4] and strides [2, 2]. Can you please recheck your conversion code on other tranposed convolutions?

https://github.com/MPolaris/onnx2tflite/blob/main/layers/conv_layers.py#L37

**Comment by MPolaris** [comment]
Yes, TFConvTranspose is problematic, only a few kinds of situation are checked.
I have no plan to fix bug for TFConvTranspose in recently, if your code can make TFConvTranspose work better, welcome PR.

**Comment by MPolaris** [comment]
Fixed
