### ISSUE TITLE
Yolov7 problem

### ISSUE THREAD

**Issue by triptec** [MPolaris/onnx2tflite#25]
I'm trying to run yolov7 using tflite.
First I export with:
```python export.py --weights ../models/yolov7/yolov7-tiny.pt --grid --simplify```

Then I run
```python converter.py --weights ../models/yolov7/yolov7-tiny.onnx --outpath ../models/yolov7/  --int8```

Finaly I run (using https://github.com/ultralytics/yolov5/blob/master/detect.py)
```python detect.py --weights ../models/yolov7/yolov7-tiny.tflite --conf 0.25 --img-size 640 --source data/images/zidane.jpg```

And it results in this:
![zidane](https://user-images.githubusercontent.com/240159/205096883-7fd0df85-5d03-4f3f-9490-7d9582eff319.jpg)

Do you have a example detect.py that works with the converted tflite models so I can figure out what I'm doing wrong?

**Comment by MPolaris** [comment]
The output's format is channel last(1, 85, 25200), not channel first like onnx or pytorch (1,  25200, 85). It maybe make error.

**Comment by triptec** [comment]
@MPolaris yes you are correct.
If I do a transpose I get the correct labels, but still I get the wrong coordinates of the boxes.
I'll see if I can show it.

**Comment by triptec** [comment]
yolov5 does a "y[0][..., :4] *= [w, h, w, h] # xywh normalized to pixels" (https://github.com/ultralytics/yolov5/blob/master/models/common.py#L581)
If I comment that out it works.

So thanks for your help!
