### ISSUE TITLE
Acknowledgement for your tool

### ISSUE THREAD

**Issue by PINTO0309** [MPolaris/onnx2tflite#26]
Hello Author. 

Your repository implementation has helped me a lot. Perhaps the repository mentioned in the README refers to the tool I created, but I have already included the quoted comment in the source code a few days ago as a thank you to you.
https://github.com/PINTO0309/onnx2tf/blob/71fa4e112440a5a604b1e99a794a77699bfcded4/onnx2tf/ops/MaxPool.py#L127-L137

I was unaware that your useful tools existed and accidentally started creating my own tools.

I am sorry if I have caused you any discomfort. I do not intend to interfere with your activities at all. I myself find your tool very easy to handle.

My tool is very different in concept from onnx2tflite because I am very conscious of implementing as many means of avoiding conversion errors as possible, instead of allowing for code complexity. I am aware that my code is too complex and probably very difficult for other engineers, except you, to understand. Therefore, I have no intention of attracting many people to my side of the tool.

If a model could not be converted by your tool, there were several times when an issue was posted on my side of the tool, and I would try to politely respond to the issue. Since your repository is by far the more popular, I don't feel any desire to be a counter-rival now. I also do not expect any more Star in my repository.

I have not been able to find a way to contact you by DM or other means, so I am posting this issue to express my gratitude to you.  If even this issue offends you, you may delete it.

Short sentences do not do a good job of conveying to you how I usually think.

Thank you again.

**Comment by MPolaris** [comment]
you are welcome.
