### ISSUE TITLE
onnx转tflite报错

### ISSUE THREAD

**Issue by YouTianlong** [MPolaris/onnx2tflite#29]
十分抱歉，打扰了。我是一个Android开发工程师，我对这块不太熟，还请多包涵。
我想把一个onnx的模型转成tflite，在手机上跑一下，测下性能。
1.我执行了python converter.py --weights "./mypose.onnx" --outpath "./" --formats "tflite"
结果报ReduceSum操作符没有实现，我看你有写怎么自定义操作符，我就在mathematics_layers.py这个文件中添加了一些代码
![image](https://user-images.githubusercontent.com/11797662/207253255-0b3578ce-dffe-4439-9b9b-f3061299b996.png)

2.之后，不会再报RecuceRum的错误了，但是会报以下错误
![image](https://user-images.githubusercontent.com/11797662/207253536-adeae078-e0e5-4bdc-9d8a-6bbed91cec1f.png)
不太懂这个问题要怎么解决，谢谢

**Comment by MPolaris** [comment]
目前来看，你的ReduceSum是写正确了的，应该是后面的算子出现了问题。
能分享一下ONNX吗？

**Comment by MPolaris** [comment]
或者你可以尝试一下其它的工具
比如https://github.com/onnx/onnx-tensorflow
或者https://github.com/PINTO0309/onnx2tf

**Comment by MPolaris** [comment]
理解保密需求，我的工具可以截断转换模型，你可以一步一步的转换，看看是哪一步shape转出错了，然后针对性的修改对应的算子代码。
```python
python converter.py --weights "./your_model.onnx" --outpath "./save_path" --formats "tflite" --input-node-names "layer_name"
```

**Comment by YouTianlong** [comment]
截取到Reshape_150，结果是这样的，看似之前就不对了
![image](https://user-images.githubusercontent.com/11797662/207273693-a5f3bd64-d86b-450f-9c37-decb5d56f083.png)

我往上找了找，猜测是这里出了问题
![image](https://user-images.githubusercontent.com/11797662/207274176-2ce7153d-7e90-4f38-b5da-518c5c61aca9.png)
![image](https://user-images.githubusercontent.com/11797662/207274402-302813bc-4b6f-4cb0-b5ac-56bd4a7ee6d8.png)

**Comment by MPolaris** [comment]
我没有太看明白这个图，不过你需要知道ONNX和TFLITE的某些算子(比如卷积conv)使用的数据排列不太一样，ONNX是ChannelFirst、TFLITE是ChannelLast，比如一个矩阵的维度是batchsize=1, channel=3, h=112, w=224，那么在ONNX里面维度是(1, 3, 112, 224)，在tflite里面是(1, 112, 224, 3)。

**Comment by YouTianlong** [comment]
进一步debug了，截断这个add算子
![image](https://user-images.githubusercontent.com/11797662/207276181-8b7c5626-134c-4942-bb16-fecb693cd4ab.png)


看似输出没问题
![image](https://user-images.githubusercontent.com/11797662/207276384-21d52cde-4797-401e-a32d-2d60f5fcb4f3.png)

阶段add左下的ConvTranspose
![image](https://user-images.githubusercontent.com/11797662/207276696-5d6bb4d9-59fe-42fe-b04e-bd1db0faa8c5.png)


结果是
![image](https://user-images.githubusercontent.com/11797662/207276858-29d3a5b8-f8d9-4708-93d2-018216f15ce0.png)

这样有帮助吗

**Comment by MPolaris** [comment]
应该是ConvTranspose这个算子转换错误了，ConvTranspose转置卷积因为ONNX和TFLITE的实现方式有一定的差异，导致这一块一直有问题。
你可以试着调试一下conv_layers.py里面的ConvTranspose算子代码，主要是self.pad那一块，目前是做了一些Crop，这种方式还还不太适合你这种情况，你主要是要保证输出维度对上就好。

**Comment by YouTianlong** [comment]
好的，十分感激，由于我不会python代码，我需要研究一下
