### ISSUE TITLE
Failed to convert dimension of right operand of multiplication

### ISSUE THREAD

**Issue by Lorilin7** [MPolaris/onnx2tflite#36]
Hello, 
I have an ONNX model that needs to be converted to TFLITE, Here is the command I use:
`python3 converter.py --weights "./model.onnx" --outpath "./save_path" --formats "tflite"`
but the error message is as follows when converting:
`Dimensions must be equal, but are 128 and 3 for '{{node tf.math.multiply_1/Mul}} = Mul[T=DT_FLOAT](Placeholder, tf.math.multiply_1/Mul/y)' with input shapes: [1,128,128,3], [3,128,128].`
It seems that the input of the multiplication operator has been transformed, but the second operand has not been dimensionally transformed, resulting in inconsistent dimensions?
Looking forward to your reply.

**Comment by MPolaris** [comment]
ops, it's a tormenting problem to match channel.
Can you share onnx to me? I need it to fix bug.
