### ISSUE TITLE
更新github代码后，以前能转换的模型现在无法转换了

### ISSUE THREAD

**Issue by PaulX1029** [MPolaris/onnx2tflite#37]
Traceback (most recent call last):
  File "/mnt/sda/AI/onnx2tflite-main/converter.py", line 70, in <module>
    run()
  File "/mnt/sda/AI/onnx2tflite-main/converter.py", line 66, in run
    image_root=opt.imgroot
  File "/mnt/sda/AI/onnx2tflite-main/converter.py", line 18, in onnx_converter
    keras_model = keras_builder(model_proto, input_node_names, output_node_names)
  File "/mnt/sda/AI/onnx2tflite-main/utils/builder.py", line 81, in keras_builder
    raise KeyError(f"{op_name} not implemented yet")
KeyError: 'Shape not implemented yet'

**Comment by PaulX1029** [comment]
链接: https://pan.baidu.com/s/1Eg2DX0VDThLOBygOV8k_KQ?pwd=vijp 提取码: vijp

**Comment by PaulX1029** [comment]
> 链接: https://pan.baidu.com/s/1Eg2DX0VDThLOBygOV8k_KQ?pwd=vijp 提取码: vijp

这是之前能正常转为tflite的onnx模型文件，转换参数如下：
![image](https://user-images.githubusercontent.com/77143808/227827362-a7d11c75-db7f-4e97-bea6-7317c53bc680.png)

**Comment by MPolaris** [comment]
看样子，你是没有打开simplify，以至于没有优化掉shape这个算子。
```python
onnx_converter(
    onnx_model_path = "./mymodel.onnx",
    need_simplify = True, #这里打开。
    output_path = "./",
    target_formats = ['tflite'], #or ['keras'], ['keras', 'tflite']
    weight_quant = False,
    int8_model = True, # do quantification
    int8_mean = [123.675, 116.28, 103.53], # give mean of image preprocessing 
    int8_std = [58.395, 57.12, 57.375], # give std of image preprocessing 
    image_root = "./dataset/train" # give image folder of train
)
