### ISSUE TITLE
Failed to initialize detector

### ISSUE THREAD

**Issue by manhlt1990** [MPolaris/onnx2tflite#4]
Failed to initialize detector. Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

**Comment by MPolaris** [comment]
Are you sure that error cause by this project? 
I can't figure error out occurs on which part...

**Comment by manhlt1990** [comment]
> Are you sure that error cause by this project? I can't figure error out occurs on which part...

I was convertd to .tflite successfully, and then run that on android => tensorflow lite throw that error.
and now I have an other error when rebuild .tflie

![image](https://user-images.githubusercontent.com/18260709/182181998-76e964a4-183e-4cb0-aec5-cf45b48ce21d.png)

**Comment by MPolaris** [comment]
For error on android, maybe you can try running tflite model on PC firstly, and select lastest or nightly(I guess) version tensorflow.
For last question, it seems your python or tensorflow environment was error, you should reinstall requirments. Tensorflow version >=2.5, recommend 2.8 or 2.9
