### ISSUE TITLE
Convert onnx with dynamic input shape

### ISSUE THREAD

**Issue by alexg93333** [MPolaris/onnx2tflite#40]
I am running into this error. It would be great if somebody could help.

python3.10 converter.py --weights "./model.onnx" --formats "tflite" --int8

> Checking 0/1...
> WARNING:onnx_loader running::onnxsim is failed, maybe make convert fails.
> Traceback (most recent call last):
>   File "/home/dockerpaddle/Desktop/onnx2tflite/converter.py", line 108, in <module>
>     run()
>   File "/home/dockerpaddle/Desktop/onnx2tflite/converter.py", line 92, in run
>     onnx_converter(
>   File "/home/dockerpaddle/Desktop/onnx2tflite/converter.py", line 21, in onnx_converter
>     keras_model = keras_builder(model_proto, native_groupconv)
>   File "/home/dockerpaddle/Desktop/onnx2tflite/utils/builder.py", line 82, in keras_builder
>     tf_tensor[node_outputs[index]] = tf_operator(tf_tensor, onnx_weights, node_inputs, op_attr, index=index)(_inputs)
>   File "/home/dockerpaddle/Desktop/onnx2tflite/layers/conv_layers.py", line 57, in __init__
>     out_channel, in_channel = node_weights[node_inputs[1]].shape[:2]
> KeyError: 'conv2d_0.w_0'

**Comment by MPolaris** [comment]
Can you share onnx to me?
I need more information about model to fix this error.

**Comment by MPolaris** [comment]
fixed, please pull latest code and try again
