### ISSUE TITLE
尝试把IMDN和RFDN的PyTorch模型转换成.tflite文件，使用AI benchmark APP简单部署在安卓手机测试速度，失败了！！！

### ISSUE THREAD

**Issue by Quanyin-li** [MPolaris/onnx2tflite#42]
代码可以运行，但是会出现这样的warning
![image](https://user-images.githubusercontent.com/61309574/236121286-8a67d214-0799-4430-981e-4d967bed619e.png)

**Comment by Quanyin-li** [comment]
这是IMDN的github仓库
https://github.com/Zheng222/IMDN

**Comment by MPolaris** [comment]
工具只负责模型转换和简单的校验功能哦。
首先在最后工具报了Warning，转换是成功了，但是模型运行失败了，需要自己检查是哪里的问题。
你可以检查是否生成了tflite文件，使用netron查看。
然后使用`tf.lite.Interpreter`来检查模型是否能正确加载和推理。
其次不同版本的tensorflow也会导致推理失败哦，比如组卷积支持度的问题。

**Comment by Quanyin-li** [comment]
我发现了问题所在：
1.您的代码不支持这个超分辨率常用的操作，pixel_shuffle = nn.PixelShuffle(upscale_factor)，删除后得到的.tflite文件在AI benchmark APP就可以run。这一处，需要将这个函数用DepthToSpace来替换
2.您的代码不支持GELU激活函数，改成Leaky ReLU函数即可

**Comment by MPolaris** [comment]
1. 在ONNX中，对应nn.PixelShuffle的操作是DepthToSpace算子(layers/deformation_layers.py#179)，而onnx2tflite是支持这个算子的，你应该检查torch.onnx.export的ONNX算子是否正确映射了该算子。
2. 你可以在layers/activations_layers.py中自行实现GELU激活函数，非常简单。
