### ISSUE TITLE
Add option to allow for dynamic resize

### ISSUE THREAD

**Issue by Marcelo5444** [MPolaris/onnx2tflite#45]
Hi!

I have been using your repo lately and managed to implement dynamic resize, could we do a PR about this and included in main

Greetings!

**Comment by MPolaris** [comment]
of course, welcome PR

**Comment by Marcelo5444** [comment]
Cant create a branch in your repo...

**Comment by MPolaris** [comment]
you can fork it to your repo , then push code to your repo and make a PR at the last.

**Comment by MPolaris** [comment]
Thanks for your PR, it's a good way for dynamic resize.
