### ISSUE TITLE
ValueError: Layer p_re_lu weight shape (1, 1, 32) is not compatible with provided weight shape (32, 1, 1).

### ISSUE THREAD

**Issue by liziru** [MPolaris/onnx2tflite#47]
![image](https://github.com/MPolaris/onnx2tflite/assets/34911790/ae5c64e6-8376-40ad-9e1e-105b04ae32e7)
![image](https://github.com/MPolaris/onnx2tflite/assets/34911790/b1a7d6c8-e33e-4491-bc45-65dc72f89acf)
My model is a unet+crn arch, any advice to solve this error?

**Comment by MPolaris** [comment]
you can debug `layers\activations_layers.py` #63-#75 lines.

**Comment by liziru** [comment]
> you can debug `layers\activations_layers.py` #63-#75 lines.

感谢，已解决，但发现KeyError: 'LSTM not implemented yet'问题，有没有支持lstm、gru的计划啊？

**Comment by MPolaris** [comment]
目前没有计划，你可以自己尝试添加。
