### ISSUE TITLE
Unable to perform 1dconv conversion?

### ISSUE THREAD

**Issue by l1uw3n** [MPolaris/onnx2tflite#56]
My onnx is as shown below. It is a model stacked by mobilenet 1D convolution. When I convert it, I get conv2d?

<img width="308" alt="image" src="https://github.com/MPolaris/onnx2tflite/assets/24247258/95d820dd-17a4-4be9-94e5-32456e0cb4af">
<img width="388" alt="image" src="https://github.com/MPolaris/onnx2tflite/assets/24247258/7c89352a-b0ba-43a6-843c-739a851a9960">

**Comment by MPolaris** [comment]
Is it check passed? If check is pass, maybe it was a optimization scheme of tflite.
