### ISSUE TITLE
onnx转为tflite 为啥数据类型变成了uint8？

### ISSUE THREAD

**Issue by sssssshf** [MPolaris/onnx2tflite#59]
脚本转换值令：
python converter.py --weights "./best.onnx" --formats "tflite" --int8 --imgroot "./data" --int8mean 0 0 0 --int8std 255 255 255
![image](https://github.com/MPolaris/onnx2tflite/assets/68574922/44853955-9dbd-4108-bac5-2a98976a7557)

**Comment by MPolaris** [comment]
有什么不对吗？如果你想使用int8的话，可以在[这里](https://github.com/MPolaris/onnx2tflite/blob/main/utils/builder.py#110)将tf.uint8更改为tf.int8
