### ISSUE TITLE
onnx转tflite 如何让维度保持不变

### ISSUE THREAD

**Issue by zhang13359** [MPolaris/onnx2tflite#63]
我用https://netron.app/ 打开model.tflite时，发现里面多了一个Transpose，它将(1,28,28,1)转换为了(1,1,28,28)，我并不想让他转换

**Comment by MPolaris** [comment]
因为pytorch和onnx数据格式基本都是channel first的，而tensorflow是channel last的。因此你只需要对输出做一个tranpose。
