### ISSUE TITLE
可以在转换的时候做fp16量化吗

### ISSUE THREAD

**Issue by dengwhao** [MPolaris/onnx2tflite#66]
好像没看到现在的代码有这个参数，int8精度损失太大了

**Comment by MPolaris** [comment]
目前你可以自行修改`builder.py`
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`
`converter.target_spec.supported_types = [tf.float16]`

**Comment by MPolaris** [comment]
你现在可以更新onnx2tflite，在转换的时候设置`fp16_model=ture`
