### ISSUE TITLE
ValueError: Unrecognized keyword arguments passed to Conv2D: {'weights': [array([[[[-2.05928516e-02, -1.33914594e-02, -1.65286055e-03, ...,

### ISSUE THREAD

**Issue by feff2** [MPolaris/onnx2tflite#67]
I tried to convert TrOCR in onnx format to tf lite, but convert.py throw such a strange mistake

**Comment by MPolaris** [comment]
maybe your tensorflow version is too high.

**Comment by avatarrokuaskingquestions** [comment]
I can get rid of this error by using tensorflow 2.15.1, as of right now everyone will have to change this locally. @MPolaris could you update the requirements file so the users don't have to make this change manually?

**Comment by MPolaris** [comment]
> I can get rid of this error by using tensorflow 2.15.1, as of right now everyone will have to change this locally. @MPolaris could you update the requirements file so the users don't have to make this change manually?

thanks for your suggestion, I will update `requirements.txt` later.
