### ISSUE TITLE
用了博主说的官方onnx-tf和这个onnx2tflite做了yolox_tiny的对比

### ISSUE THREAD

**Issue by zxccsssd** [MPolaris/onnx2tflite#72]
![yolox_voc_tiny tflite](https://github.com/user-attachments/assets/333fbfcf-111e-4315-9d38-27cb8f6fed0b)
![yolox tflite](https://github.com/user-attachments/assets/bc2bab14-cca4-41d7-8a63-ba06dcf8df73)
![yolox_voc_tiny onnx](https://github.com/user-attachments/assets/e4319773-196a-4a0a-bb35-eb6f9e921b53)

第一幅图是用的是本项目的，第二个是用的官方的，可以看出来确实少了很多transpose操作。这方面我属于小白，我想请教下，本项目中的结尾处也有很多transpose，因为我又查看了图三的onnx模型图，后边是没有那么多transpose，所以说本项目中的结尾处是不是也有多余的？还有就是导出来的文件大小，本项目的文件大小是19M，官方的是5M，图里没有显示量化。文件的大小有什么说法吗？

**Comment by MPolaris** [comment]
从这个case看，结尾处的tranpose确实有多余。主要是需要对齐通道，现在强制在reshape的时候使用transpose转换回channel-first来进行，你也可以针对特定的情况(比如这里)写一个对应的判断从而不发生，欢迎PR。
