### ISSUE TITLE
tflite模型精度严重下降

### ISSUE THREAD

**Issue by xueyue-hd** [MPolaris/onnx2tflite#75]
您好，我将pytorch训练的mobilenetv3模型，通过onnx2tflite成功转换为tflite。然而，新格式得模型在测试集上出现严重得精度下降问题，我已经关闭了转换时得need_simplify选项，请问可能是什么原因导致这一情况出现？

**Comment by MPolaris** [comment]
need_simplify是建议开启的，对结果没有影响。
注意通道对齐，onnx模型输入和tflite的输入channel是不一样的。
