### ISSUE TITLE
onnx.py 文件中尝试导入 load_onnx_modelproto 时发生了循环导入

### ISSUE THREAD

**Issue by Wasser1462** [MPolaris/onnx2tflite#78]
from onnx2tflite import onnx_converter

res = onnx_converter(
        onnx_model_path = "/home/onnx/d-onnx/model.onnx",
        need_simplify = True,
        output_path = "/home/onnx/d-onnx/",
        target_formats = ['tflite'],
    )
onnx.py如上所示。
![image](https://github.com/user-attachments/assets/0ada70c1-c991-4958-a3af-bedec11d8ef8)

请问大佬，遇到这个问题该怎么解决啊？

**Comment by MPolaris** [comment]
我这边一切正常，这种问题自己Debug一下吧。
