### ISSUE TITLE
Error when specifying need_simplify=False when converting

### ISSUE THREAD

**Issue by enzoferrari1** [MPolaris/onnx2tflite#79]
When doing conversion of my YOLOv10 n model, an error occurs while using the converter with need_simplify = False. I don't want to quantize the model because it loses too much accuracy in the case of YOLO. 
```
from onnx2tflite import onnx_converter
res = onnx_converter(
        onnx_model_path = "/content/yolo-single-detector.onnx",
        need_simplify = False,
        fp16_model = True,
        native_groupconv = True,
        output_path = "/content",
        target_formats = ['tflite'],
    ) 
```

shows error 
```
[/content/onnx2tflite/onnx2tflite/components/builder.py](https://localhost:8080/#) in keras_builder(onnx_model, native_groupconv)
     49         # init layout
     50         for index in range(len(node_outputs)):
---> 51             layout_dict[node_outputs[index]] = layout_dict.get(node_inputs[0], Layout.Default)
     52 
     53         res = tf_operator(tf_tensor, onnx_weights, node_inputs, op_attr, node_outputs, layout_dict)(_inputs)

IndexError: list index (0) out of range
```

**Comment by MPolaris** [comment]
`need_simplify` is recommended to be enabled as it will optimize the compute graph without affecting accuracy.

**Comment by abhijeetsourav** [comment]
### The below code gives the same error

`from onnx2tflite import onnx_converter

res = onnx_converter(
        onnx_model_path = "/content/parseq.onnx",
        need_simplify = True,
        output_path = "/content/",
        target_formats = ['tflite'],
    )`

`2024-08-30 21:17:31,309 - onnx_loader running: - WARNING - onnxsim is failed, maybe make convert fails.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-85-e550f6b44428>](https://localhost:8080/#) in <cell line: 3>()
      1 from onnx2tflite import onnx_converter
      2 
----> 3 res = onnx_converter(
      4         onnx_model_path = "/content/parseq.onnx",
      5         need_simplify = True,

1 frames
[/content/onnx2tflite/onnx2tflite/components/builder.py](https://localhost:8080/#) in keras_builder(onnx_model, native_groupconv)
     49         # init layout
     50         for index in range(len(node_outputs)):
---> 51             layout_dict[node_outputs[index]] = layout_dict.get(node_inputs[0], Layout.Default)
     52 
     53         res = tf_operator(tf_tensor, onnx_weights, node_inputs, op_attr, node_outputs, layout_dict)(_inputs)

IndexError: list index (0) out of range`
