### ISSUE TITLE
YOLOv5n ONNX to TFLite export not working with `KeyError: 'onnx::Resize_448'`

### ISSUE THREAD

**Issue by glenn-jocher** [MPolaris/onnx2tflite#8]
Hi! I'm getting an error in Google Colab on attempting to convert an ONNX model to TFLite using this tool. I've attached the ONNX model causing the bug, and also provided full code to reproduce below. I tried YOLOv5n models exported to ONNX using opset 11, 12 and 13, and saw problems in all of them.

### Code to Reproduce

```python
!git clone https://github.com/ultralytics/yolov5
!git clone https://github.com/MPolaris/onnx2tflite
%pip install -qr yolov5/requirements.txt  # install

!python yolov5/export.py --weights ./yolov5n.pt --include onnx

%cd onnx2tflite
from converter import onnx_converter
onnx_converter(
    onnx_model_path = "../yolov5n.onnx",
    need_simplify = True,
    output_path = "./",
    target_formats = ['tflite'], # or ['keras'], ['keras', 'tflite']
    weight_quant = False,
    int8_model = False,
    int8_mean = None,
    int8_std = None,
    image_root = None
)
```

### Result
```bash
WARNING:onnx_loader running::模型优化失败, 从../yolov5n.onnx加载
/content/onnx2tflite/onnx2tflite
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-6-5f2991b979cc>](https://localhost:8080/#) in <module>
     16     int8_mean = None,
     17     int8_std = None,
---> 18     image_root = None
     19 )

2 frames
[/content/onnx2tflite/layers/common_layers.py](https://localhost:8080/#) in __init__(self, tensor_grap, node_weights, node_inputs, node_attribute, *args, **kwargs)
    199         else:
    200             # 从scales取
--> 201             _, _, nh, nw = node_weights[node_inputs[2]]
    202             _, h, w, _ = tensor_grap[node_inputs[0]].shape
    203             nh, nw = int(h*nh), int(w*nw)

KeyError: 'onnx::Resize_445'
```

<img width="1398" alt="Screenshot 2022-08-31 at 00 55 11" src="https://user-images.githubusercontent.com/26833433/187557634-1385cc3b-16b6-40d0-a412-059e68c54b70.png">

@ayushExel

**Comment by glenn-jocher** [comment]
Sorry, forgot to attach my ONNX model earlier. I've attached it here:

[yolov5n.onnx.zip](https://github.com/MPolaris/onnx2tflite/files/9457091/yolov5n.onnx.zip)

Model open correctly in Netron, it is the official YOLOv5 v6.2 nano model, not a custom trained model.

<img width="1136" alt="Screenshot 2022-08-31 at 00 58 47" src="https://user-images.githubusercontent.com/26833433/187558034-c6dec469-69ed-4fae-8725-db1d383f34d9.png">

**Comment by MPolaris** [comment]
> Sorry, forgot to attach my ONNX model earlier. I've attached it here:
> 
> [yolov5n.onnx.zip](https://github.com/MPolaris/onnx2tflite/files/9457091/yolov5n.onnx.zip)
> 
> Model opens correctly in Netron, it is the official YOLOv5 v6.2 nano model exported to ONNX, not a custom trained model.
> 
> <img alt="Screenshot 2022-08-31 at 00 58 47" width="1136" src="https://user-images.githubusercontent.com/26833433/187558034-c6dec469-69ed-4fae-8725-db1d383f34d9.png">

Thanks for your issue, I have tested the onnx model and successed.
The success key is you should make ```need_simplify = True```.
My code is lastest, and requirments' version as follow:
```
python 3.8
tensorflow 2.8.0
onnx 1.11.0
onnx-simplifier 0.3.8
```

**Comment by glenn-jocher** [comment]
@MPolaris awesome, thanks for the help! Your solution works. Code to reproduce correct export:

```python
!git clone https://github.com/ultralytics/yolov5
!git clone https://github.com/MPolaris/onnx2tflite
%pip install -qr yolov5/requirements.txt  # install

!python yolov5/export.py --weights ./yolov5n.pt --include onnx --simplify

%cd onnx2tflite
from converter import onnx_converter
onnx_converter(
    onnx_model_path = "../yolov5n.onnx",
    need_simplify = True,
    output_path = "./",
    target_formats = ['tflite'], # or ['keras'], ['keras', 'tflite']
    weight_quant = False,
    int8_model = False,
    int8_mean = None,
    int8_std = None,
    image_root = None
)
```

**Comment by MPolaris** [comment]
@glenn-jocher I'm glad to help you and please star this repository, thanks for your issue again.
