### ISSUE TITLE
转换的时候报了一些问题

### ISSUE THREAD

**Issue by fansangg** [MPolaris/onnx2tflite#83]
Checking 0/1...
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 84). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: C:\Users\KCST\AppData\Local\Temp\tmpt5qu9yh7\assets
INFO:tensorflow:Assets written to: C:\Users\KCST\AppData\Local\Temp\tmpt5qu9yh7\assets
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING:converter running::tflite model elements' max error is 6.1035E-04, pass, tflite saved in ./best.tflite

然后我使用转换后的tflite文件，在Android平台使用MLKit，报错Failed to initialize detector. Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

请问大佬这个是怎么回事，弟弟是小白，刚刚涉足这个方面，望指教

**Comment by miguellords** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by MPolaris** [comment]
onnx2tflite只是一个帮助你转换模型格式的工具，看结果信息转换是成功的，也就是模型是正确的。
此外我看了一下你这个报错，应该是跟MLKit有关，大概是模型需要的是NormalizationOptions处理过的metadata类型的信息，而你直接输入了kTfLiteFloat32（应该就是图片数据本身），你应该看看这个MLKit的具体使用方法。
